AWSTemplateFormatVersion: "2010-09-09"
Description: "(2) Amazon MSK Clusters for Poloniex Perf tests"
Resources:
    MSKCluster3AZ:
        Type: "AWS::MSK::Cluster"
        Properties:
            ClusterName: "Cluster-3AZ-3BRK"
            NumberOfBrokerNodes: 3
            Tags: {}
            EnhancedMonitoring: "PER_TOPIC_PER_BROKER"
            EncryptionInfo:
                EncryptionAtRest:
                    DataVolumeKMSKeyId: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/000-111-222-333-444-555..."
                EncryptionInTransit:
                    ClientBroker: "TLS"
                    InCluster: true
            KafkaVersion: "2.8.1"
            ConfigurationInfo:
                Arn: !Sub "arn:aws:kafka:${AWS::Region}:${AWS::AccountId}:configuration/custom-configuration/000-111-222-333-444-555..."
                Revision: 1
            ClientAuthentication:
                Sasl:
                    Scram:
                        Enabled: false
                    Iam:
                        Enabled: true
                Tls:
                    Enabled: false
                Unauthenticated:
                    Enabled: false
            BrokerNodeGroupInfo:
                BrokerAZDistribution: "DEFAULT"
                ClientSubnets:
                  - "subnet-000..."
                  - "subnet-111..."
                InstanceType: "kafka.m5.4xlarge"
                SecurityGroups:
                  - "sg-000..."
                  - "sg-111..."
                StorageInfo:
                    EBSStorageInfo:
                        VolumeSize: 5000
            OpenMonitoring:
                Prometheus:
                    JmxExporter:
                        EnabledInBroker: true
                    NodeExporter:
                        EnabledInBroker: false
            LoggingInfo:
                BrokerLogs:
                    CloudWatchLogs:
                        Enabled: false
                    Firehose:
                        Enabled: false
                    S3:
                        Enabled: false

    MSKCluster2AZ:
        Type: "AWS::MSK::Cluster"
        Properties:
            ClusterName: "Cluster-2AZ-4BRK"
            NumberOfBrokerNodes: 4
            Tags: {}
            EnhancedMonitoring: "PER_TOPIC_PER_BROKER"
            EncryptionInfo:
                EncryptionAtRest:
                    DataVolumeKMSKeyId: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/000-111-222-333-444-555..."
                EncryptionInTransit:
                    ClientBroker: "TLS"
                    InCluster: true
            KafkaVersion: "2.8.1"
            ConfigurationInfo:
                Arn: !Sub "arn:aws:kafka:${AWS::Region}:${AWS::AccountId}:configuration/custom-configuration/000-111-222-333-444-555..."
                Revision: 1
            ClientAuthentication:
                Sasl:
                    Scram:
                        Enabled: false
                    Iam:
                        Enabled: true
                Tls:
                    Enabled: false
                Unauthenticated:
                    Enabled: false
            BrokerNodeGroupInfo:
                BrokerAZDistribution: "DEFAULT"
                ClientSubnets:
                  - "subnet-000..."
                  - "subnet-111..."
                InstanceType: "kafka.m5.4xlarge"
                SecurityGroups:
                  - "sg-000..."
                  - "sg-111..."
                StorageInfo:
                    EBSStorageInfo:
                        VolumeSize: 5000
            OpenMonitoring:
                Prometheus:
                    JmxExporter:
                        EnabledInBroker: false
                    NodeExporter:
                        EnabledInBroker: false
            LoggingInfo:
                BrokerLogs:
                    CloudWatchLogs:
                        Enabled: false
                    Firehose:
                        Enabled: false
                    S3:
                        Enabled: false
